Spring boot security
dizizzz/spring-boot pull request #7
Opened 2024-01-21 23:42 UTC by dizizzz

2024-01-22 15:29 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution 😉

2024-01-22 15:29 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springboot/dto/UserRegistrationRequestDto.java
> +})
```suggestion
@FieldsValueMatch(
        field = "password",
        fieldMatch = "verifyPassword",
        message = "Password mismatch"
)
```
you can simplify  it (check next comment)

2024-01-22 15:29 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springboot/validation/FieldMatch.java
> +    }
```suggestion
```

2024-01-22 15:29 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springboot/exception/RegistrationException.java
> +public class RegistrationException extends RuntimeException {
this exception should extend the Exception class

2024-01-22 15:29 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springboot/repository/user/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Repository annotation is missed

2024-01-22 15:29 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springboot/service/imlpl/UserServiceImpl.java
> +            throw new RegistrationException("Can`t register user");
```suggestion
            throw new RegistrationException("Can`t register user by email: ", email);
```
better make a message more informative

2024-01-22 15:29 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springboot/service/imlpl/UserServiceImpl.java
> +        if (userRepository.findByEmail(requestDto.getEmail()).isPresent()) {
you also can use the repository method `existByEmail` and simplify this conditional ;)

2024-01-22 15:29 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springboot/service/imlpl/UserServiceImpl.java
> +        user.setShippingAddress(requestDto.getShippingAddress());
this is the logic of the mapper

2024-01-22 15:29 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springboot/validation/FieldMatchValidator.java
> +        }
you can use the ternary operator here 
```suggestion
        return fieldValue != null && fieldValue.equals(fieldMatchValue);
```

2024-01-22 15:29 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/02-create-users-table.yaml
```suggestion
      file: db/changelog/changes/02-create-users-table.yaml
      
```
Leave one empty line at the end of the file

2024-01-23 10:30 UTC, Rommelua commented on src/main/java/mate/academy/springboot/validation/FieldMatchValidator.java
> +        return fieldValue != null && fieldValue.equals(fieldMatchValue);
Objects.equals()

2024-01-23 19:10 UTC, merged